---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: olleh
    namespace: hello
    annotations:
      flux.weave.works/automated: 'true'
  spec:
    minReadySeconds: 1
    replicas: 5
    template:
      metadata:
        labels:
          name: ollehworld
      spec:
        containers:
        - name: ollehworld
          image: quay.io/weaveworks/helloworld:master-07a1b6b
          args:
          - -msg=OLLEH
          ports:
          - containerPort: 80
        - name: sidecar
          image: quay.io/weaveworks/sidecar:master-a000002
          args:
          - -addr=:8080
          ports:
          - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: olleh
    namespace: hello
  spec:
    ports:
    - port: 80
    selector:
      name: olleh
